env:
  global:
    - REPO_DIR=onnx
    - BUILD_COMMIT=553df22c67bee5f0fe6599cff60f1afc6748c635
    - PLAT=x86_64
    - PB_VERSION=2.6.1
    - UNICODE_WIDTH=32
    - REPO=https://upload.pypi.org/legacy/
    - TEST_REPO=https://test.pypi.org/legacy/
    - secure: lWCQK9r2j9iygJCc75d0++ORD0tEPowFO0MD6ytloNOnoz1rEhZAnGdYBk+SIC6lgxGDisK04Zi/cQ5P6/VdBU41leQdFrqgpnhJ/Da8+pFb+PS0lwz2BS7k4jM+UM905mJ/xLUEokSwP3BkYJZj8Ql1/gXNbaz0UQeUFFoceK7kgLCYqUpgnTihfcHMiCz1wVMpEzixE66asoDbSI3C2qzhqBoO9S7UOnXXQLdYZbn83uHvuPaSTUt3mKs7c9j4756+T1bwsNdInv7vXY72qSbcLJOf7i7Y/1HbwOcudFIyOoUr/N7tIqqHOu0yS/OsGg1OCl9PVUS8GkyYsk2QKW+BhExdVQgYb5oB2OLNpjPIXNx/bL6Bis9y2gC4HN9vTW58Ep7OiEvxzpAW0xITDdrtS7GrKXlX2tRo+3vj6CtQLdoOUCpno7UfQpdDzMPSyeKUQHFOtNtZRiY5KHQTEKIUhMyXxRq02umH0jRZGIcugw5WnbFfNttVZwxSMf2ghGATIlXPj56vP+5BTOuMFMfPmoZxDR50zrvA5+LO5CdR3xlD+18M0NoOVac0DADGn7y27cXJeMRnqaNLIqojyrFPX1VXwI/B7t9BY1PYrsyT983U4kRsPD46R7v7PMrXLnwX0ux6OphTghuOX8SF2l3erLlr7Ef33cAUAPMzzso=
    - secure: I+8Xw/IJxUKCVRlzaZTlW0Khmq9Gvn7cbCom//svufstOKaVQTCD+mE83Hdp6kZKQugLSTXbrjMjSMM1ur5R9CCqNowL7tNP2bMgj5leFg+/LYDFKTG/bezoOdeWFtjODtSNIbvhr06HJpKCBg98x8go6drB5UUbYjLmlzpgBBnnN27Zbl3Wd8xhYlJa4IPSARLmv5L+gqRNbShbhlttD1fnPIlBuQ2uGSHwclDEC8tXAowU0MJ+JD9LFnJxOuwX1AqarYj6oAVFa86ll4sRSVSmQe2mFnXp1JX9trbWTzYoQ2DwS4QTIo6/76+yLpi0L2hlWRbvMWT7zEtPTAB4crLn1aZDcWf1FoDPXMCgX93i6fM4RantVgFKvSOEJdsWGqSnseUW0Y7qXcbew+xOYGkSYifZRVrl/QAW0nMYx3r0TR+zPM42mBWK/iBR9WpRKWvdTJGPRm8lUc6JkyolgsRMSswtIYJ9x6iNs59zEYjpqNmYxMZ1PBoy4qPPHLLw8Q1m2p871G3t4kY2y690vDTOgx7Ctwj3tF2+2QO3J+D6aPupIPkmI5twk6aJIdGVxCJhcAnGRCaTL1BZPcG3Je0YN++OBirxlJuS7cA4sAg0Lzt9WymzFfG4VH8tCU5gxr0nwDltNeEA2TWan+UNgtSZ/ststU1Udj7qbvOLvDE=
language: python
# Default Python version is usually 2.7
python: 3.5
sudo: required
dist: trusty
services: docker
# Force xcode 6.4 image to work round
# https://github.com/python-pillow/pillow-wheels/issues/45
# So we have the line below for OSX builds
# osx_image: xcode9.3beta
matrix:
  # Exclude the default Python 3.5 build
  exclude:
  - python: 3.5
  include:
  - os: osx
    language: generic
    sudo: required
    osx_image: xcode9.3beta
    env:
      - MB_PYTHON_VERSION=3.5
      - ONNX_ML=1
      - MACOSX_DEPLOYMENT_TARGET=10.9
  - os: osx
    language: generic
    sudo: required
    osx_image: xcode9.3beta
    env:
      - MB_PYTHON_VERSION=3.6
      - ONNX_ML=1
      - MACOSX_DEPLOYMENT_TARGET=10.9
  - os: osx
    language: generic
    sudo: required
    osx_image: xcode9.3beta
    env:
      - MB_PYTHON_VERSION=3.7
      - ONNX_ML=1
      - MACOSX_DEPLOYMENT_TARGET=10.9
  - os: osx
    language: generic
    sudo: required
    osx_image: xcode9.3beta
    env:
      - MB_PYTHON_VERSION=2.7
      - ONNX_ML=1
      - MACOSX_DEPLOYMENT_TARGET=10.9
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=2.7 
      - ONNX_ML=1 
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=2.7 
      - ONNX_ML=1 
      - UNICODE_WIDTH=16 
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=2.7 
      - ONNX_ML=1 
      - PLAT=i686 
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=2.7 
      - ONNX_ML=1 
      - UNICODE_WIDTH=16 
      - PLAT=i686 
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=3.5 
      - ONNX_ML=1 
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=3.6 
      - ONNX_ML=1 
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=3.7 
      - ONNX_ML=1 
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=3.5 
      - ONNX_ML=1 
      - PLAT=i686 
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=3.6 
      - ONNX_ML=1 
      - PLAT=i686
  - os: linux 
    sudo: required 
    env: 
      - MB_PYTHON_VERSION=3.7 
      - ONNX_ML=1 
      - PLAT=i686

before_install:
  - source multibuild/common_utils.sh;
  - source multibuild/travis_steps.sh;
  - before_install;

install:
  - clean_code $REPO_DIR $BUILD_COMMIT;
  - build_wheel $REPO_DIR $PLAT;

script:
  - install_run $PLAT

after_success:
- >
  if [ -n "$TRAVIS_TAG" ]; then
    pip install twine;
    pip install pyOpenSSL ndg-httpsclient pyasn1 || true;
    python -m twine upload --skip-existing ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl --repository-url $REPO -u $PYPI_USERNAME_TRAVIS -p $PYPI_PASSWORD_TRAVIS ;
    echo "Deployed to PyPI.";
  else
    echo "Not deploying as not a tagged commit.";
  fi
- >
  if [ "$TRAVIS_BRANCH" == "pypi_test" ]; then
    pip install twine;
    pip install pyOpenSSL ndg-httpsclient pyasn1 || true;
    ls ${TRAVIS_BUILD_DIR}/wheelhouse/;
    python -m twine upload --skip-existing ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl --repository-url $TEST_REPO -u $PYPI_USERNAME -p $PYPI_PASSWORD ;
    echo "Deployed to test PyPI.";
  else
    echo "Not deploying as not a commit on test branch.";
  fi

cache:
- timeout: 300
- directories:
  - "$BUILD_CCACHE_DIR"
  - "$HOME/.ccache"
  - "$HOME/.cache/pb"
